---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: echo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: echo-app
  template:
    metadata:
      labels:
        app: echo-app
    spec:
      nodeSelector:
        "beta.kubernetes.io/os": linux
      containers:
      - name: echo-app
        image: hashicorp/http-echo:latest
        args: ["-text='Hello from Azure Kubernetes Service!'"]
        ports:
        - containerPort: 5678
---
apiVersion: v1
kind: Service
metadata:
  name: echo-app
spec:
  type: LoadBalancer
  ports:
  - port: 5678
  selector:
    app: echo-app